services:
  srv-codelab:
    image: bitnami/postgresql:17.5.0
    container_name: codelab
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=codelab-db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/bitnami/postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: hilquiasfmelo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: benjamin
    ports:
      - "4435:80"  # Acesse via http://localhost:4435
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./backups:/backups  # opcional: para backups/restaurações via interface

volumes:
  postgres-data:
  pgadmin_data:
